name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2

      - name: Put project in GOPATH
        # It won't find the package otherwise because the cloned repo is outside
        # of $GOPATH or $GOROOT
        run: |
          export GOPATH=~/go
          mkdir -p ${GOPATH}/src/github.com/coaxial
          cp -r ~/work/tizinger/tizinger ${GOPATH}/src/github.com/coaxial
      
      - name: Run tests
        run: make ci
