name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2

      - name: Add module
        run: go mod init github.com/coaxial/tizinger
     
      - name: Run tests
        run: make ci
